export const message = {
  ADMIN_CREDENTIAL_ERROR: "Error While inserting admin credentials",
  LOGIN_ERROR: "Email id or Password is Wrong",
  SOMETHING_WENT_WRONG: "Something Went Wrong",
  LOGIN_ISSUE: "Please try after some time | Authentication Error",
  ACCOUNT_CREATION_SUCCESSFULL: "Account is successfully created",
  ALREADY_ACCOUNT_EXIST: "Acount is alreay exist",
  SERVER_ERROR: "Internal Server Error Please try again after sometime",
  ALL_FIELD_REQUIRED: "All Fields are required",
  ACCOUNT_LOGIN_SUCCESSFULL: "Accoutnlogin successfull",
  ADMIN_PROTECTED_ROUTE: "This is protected route for Admin",
  ALUMNI_PROTECTED_ROUTE: "This is protected route for Alumni",
  SUCCESSFULLY_ADDED: "Successfully added",
  EVENT_NOT_ADDED: "Error while Adding Event",
  EVENT_LIST_ERROR: "Error while fetching list of events",
  LIST_FETCHED_SUCCESSFULLY: "List fetched successfully",
  EVENT_DELETE_ERROR: "Error while deleting event",
  EVENT_DELETED: "Event deleted successfully",
  EVENT_UPDATED: "Event Updation Successfull",
  MAIL_SENDING_ERROR: "Error While Sending mail",
  PROFILE_UPLOAD_ERROR: "Error While Uploading Profile Pic",
  WAIT_FOR_ADMIN_APPROVAL:
    "Wait for Admin Approval till that you need to verify yourself on mail",
  MAIL_VERIFYING_ERROR: "Error occur While Verifying mail",
  MAIL_VERIFICATION_SUCCESSFULL: "Mail Verification successs full",
  ADMIN_VERIFICATION_SUCCESSFULL: "Admin Verification successfull",
  ACCOUNT_CLOSED:
    "Your Account is closed If you want to optn please contact Admin",
  JOB_ADDITION_SUCCESSFULL: "Job Posting Successfull",
  JOB_ADMIN_VIEW_SUCCESS: "JOb fetched successfully",

  USER_NOT_FOUND: "Your Account doesn't  exist signup your account",
  ALUMNI_DATA_FETCHED: "Alumni data fetched successfully",
  ALUMNI_JOB_DATA_FETCHED: "Your job is successfully fetched",
  ALL_JOB_DATA_FETCHED: "All Job data fetched Successfull",
  JOB_DELETION_SUCCESSFULL: "Job deleted successfully",
  ALUMNI_NOT_FOUND: "Alumni Not Found",
  ALUMNI_DATA_FETCHED: "Alumni data fetched",
  UNAUTHORIZED: "Reject due to UnAuthorized Access",
  JOB_REMOVED_SUCCESSFULLY: "Job Removed successfully",
  JOB_DATA_FETCHED: "Job Data Fethced",
  JOB_UPDATED_SUCCESSFULLY: "Job Updated Successfully",
  JOB_NOT_FOUND: "Job Not Found",

  FORUM_ADDED: "Forum added successfully",
  ALUMNI_GET_MY_FORUM_SUCCESS: "Froum data fetched",
  FORUM_NOT_FOUND: "Forum Not found",
  FORUM_UPDATE_SUCCESSFULL: "Forum Updated Successfull",
  FORUM_REMOVE_SUCCESSFULL: "Forum Remove Successfull",
  FORUM_ALREADY_JOINED: "Already joined in forum",
  FORUM_JOINED: "You are Joined in the Forum",
  FORUM_DELETED: "Forum deleted successfull",
  FORUM_DATA_FETCHED: "Forum data fetched",
  
  FORUM_CHAT_SEND: "Message Sent",
  FORUM_CHAT_FETHCED : "Forum chat fetched successfull"
};

export const statusCode = {
  SUCCESS: 200,
  ERROR: 500,
  NOT_FOUND: 404,
  ALREADY_EXIST: 409,
  UNAUTHORIZED: 401,
  REQUIRED: 401,
};
