export const message = {
  ADMIN_CREDENTIAL_ERROR: "Error While inserting admin credentials",
  LOGIN_ERROR: "Email id or Password is Wrong",
  SOMETHING_WENT_WRONG: "Something Went Wrong",
  LOGIN_ISSUE: "Please try after some time | Authentication Error",
  ACCOUNT_CREATION_SUCCESSFULL: "Account is successfully created",
  ALREADY_ACCOUNT_EXIST: "Acount is alreay exist",
  SERVER_ERROR: "Internal Server Error Please try again after sometime",
  ALL_FIELD_REQUIRED: "All Fields are required",
  ACCOUNT_LOGIN_SUCCESSFULL: "Accoutnlogin successfull",
  ADMIN_PROTECTED_ROUTE: "This is protected route for Admin",
  ALUMNI_PROTECTED_ROUTE: "This is protected route for Alumni",
  SUCCESSFULLY_ADDED: "Successfully added",
  EVENT_NOT_ADDED: "Error while Adding Event",
  EVENT_LIST_ERROR: "Error while fetching list of events",
  LIST_FETCHED_SUCCESSFULLY: "List fetched successfully",
  EVENT_DELETE_ERROR: "Error while deleting event",
  EVENT_DELETED: "Event deleted successfully",
  EVENT_UPDATED: "Event Updation Successfull",
  MAIL_SENDING_ERROR: "Error While Sending mail",
  PROFILE_UPLOAD_ERROR: "Error While Uploading Profile Pic",
  WAIT_FOR_ADMIN_APPROVAL: "Wait for Admin Approval till that you need to verify yourself on mail",
  MAIL_VERIFYING_ERROR: "Error occur While Verifying mail",
  MAIL_VERIFICATION_SUCCESSFULL: "Mail Verification successs full",
  ADMIN_VERIFICATION_SUCCESSFULL: "Admin Verification successfull",
  ACCOUNT_CLOSED: "Your Account is closed If you want to optn please contact Admin",
  JOB_ADDITION_SUCCESSFULL: "Job Posting Successfull",
  JOB_ADMIN_VIEW_SUCCESS : "JOb fetched successfully",
};

export const statusCode = {
  SUCCESS: 200,
  ERROR: 500,
  NOT_FOUND: 404,
  ALREADY_EXIST: 409,
  UNAUTHORIZED: 401,
  REQUIRED: 401,
};
